#!/usr/bin/env python3
"""Build only the icons used by the selected service pages; preserve glyph shapes."""
import argparse
from io import BytesIO
import json
from pathlib import Path
import re
import subprocess

from fontTools import subset
from fontTools.pens.recordingPen import RecordingPen
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parents[1]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--git-index', action='store_true', help='Read exact staged paths on case-insensitive filesystems')
    parser.add_argument('--check', action='store_true', help='Verify committed outputs without writing')
    args = parser.parse_args()
    config = json.loads((ROOT / 'scripts/performance/service-icons.json').read_text())

    def read(path):
        if args.git_index:
            return subprocess.check_output(['git', 'show', ':' + path], cwd=ROOT).decode('utf-8')
        return (ROOT / path).read_text(encoding='utf-8')

    content = '\n'.join(read(path) for path in config['pages'] + config['scripts'])
    names = sorted(set(re.findall(r'\bbi-([a-z0-9-]+)', content)))
    source_css = (ROOT / 'assets/vendor/bootstrap-icons/bootstrap-icons.css').read_text()
    codes = {name: int(code, 16) for name, code in re.findall(r'\.bi-([a-z0-9-]+)::before\s*\{\s*content:\s*"\\([a-f0-9]+)";', source_css)}
    for alias, original in config['aliases'].items():
        codes[alias] = codes[original]
    missing = set(names) - codes.keys()
    if missing:
        raise SystemExit('Unmapped service icons: ' + ', '.join(sorted(missing)))
    wanted = {codes[name] for name in names}
    font = TTFont(ROOT / 'assets/vendor/bootstrap-icons/fonts/bootstrap-icons.woff', recalcTimestamp=False, recalcBBoxes=False)
    if not wanted <= font.getBestCmap().keys():
        raise SystemExit('Required glyph is absent from the source font')
    options = subset.Options()
    options.recalc_timestamp = False
    source_glyphs = font.getGlyphSet()
    original_shapes = {}
    for code in wanted:
        glyph = source_glyphs[font.getBestCmap()[code]]
        pen = RecordingPen()
        glyph.draw(pen)
        original_shapes[code] = (pen.value, glyph.width)
    subsetter = subset.Subsetter(options=options)
    subsetter.populate(unicodes=wanted)
    subsetter.subset(font)
    font.flavor = 'woff2'
    buffer = BytesIO()
    font.save(buffer)
    font_bytes = buffer.getvalue()
    rebuilt = TTFont(BytesIO(font_bytes))
    if not wanted <= rebuilt.getBestCmap().keys():
        raise SystemExit('Required glyph is absent from the generated font')

    generated_glyphs = rebuilt.getGlyphSet()
    for code in wanted:
        glyph = generated_glyphs[rebuilt.getBestCmap()[code]]
        pen = RecordingPen()
        glyph.draw(pen)
        if (pen.value, glyph.width) != original_shapes[code]:
            raise SystemExit(f'Icon outline or advance width changed: {code:x}')

    # Keep the original icon metrics and family; only the loaded glyph set differs.
    base_rules = source_css[source_css.index('[class^='):source_css.index('.bi-alarm-fill')].strip()
    css = '/* Bootstrap Icons (MIT); generated by scripts/build_service_icons.py */\n'
    css += '@font-face{font-family:"bootstrap-icons";font-display:swap;src:url("../vendor/bootstrap-icons/fonts/bootstrap-icons-services.woff2?v=20260930-1") format("woff2")}\n'
    css += base_rules + '\n'
    css += '\n'.join(f'.bi-{name}::before{{content:"\\{codes[name]:x}"}}' for name in names) + '\n'
    outputs = {
        'assets/css/service-icons.css': css.encode(),
        'assets/vendor/bootstrap-icons/fonts/bootstrap-icons-services.woff2': font_bytes,
    }
    for path, data in outputs.items():
        if args.check:
            actual = (ROOT / path).read_bytes()
            if path.endswith('.css'):
                actual = actual.replace(b'\r\n', b'\n')
            if actual != data:
                raise SystemExit('Stale generated asset: ' + path)
        else:
            (ROOT / path).write_bytes(data)
    print(f'PASS: {len(config["pages"])} pages, {len(names)} icon classes, {len(wanted)} glyphs, {len(font_bytes):,} font bytes')


if __name__ == '__main__':
    main()
